### ISSUE TITLE
Commands don't work

### ISSUE THREAD

**Issue by AtomicSanity** [RedPanda4552/SimpleEgg#4] opened 2019-07-22 00:39 UTC
With the version 0.4.7 commands don't seem to work, I have tried /se SimpleEgg.* and it just does nothing, I still cant catch anything. I did it in the server console.  Help!

**Comment by AtomicSanity** [comment] 2019-07-22 00:40
I have tried anything to make it work aswell, I have tried /se SimpleEgg.* Atomic_Sanity or /se SimpleEgg.* Atomic_Sanity true, I have tried so many variants and it just does not work and I have tried this for hours.

**Comment by RedPanda4552** [comment] 2019-08-23 23:56
Apologies, I only now got around to this. I just finished upgrading the API version to 1.14.4 and am unable to reproduce. Closing for now.

**Closed by RedPanda4552** 2019-08-23 23:56 UTC
